### ISSUE TITLE
Failed to activate the atom-silverstripe package

### ISSUE THREAD

**Issue by grgcnnr** [gorriecoe/atom-silverstripe#5]
After updating to 1.16 atom silverstripe is failing to start fro me with the following error:

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-silverstripe](https://github.com/gorriecoe/atom-silverstripe) package 3.0.2

### Stack Trace

Failed to activate the atom-silverstripe package

```
At dev is not defined

ReferenceError: dev is not defined
  at evalmachine.<anonymous>:1:1
  at ContextifyScript.Script.runInThisContext (vm.js:25:33)
  at Object.exports.runInThisContext (vm.js:77:17)
  at global.eval (/packages/atom-silverstripe/node_modules/loophole/lib/loophole.js:12:19)
  at /packages/atom-silverstripe/lib/logic.js:15:20
  at exports.allowUnsafeEval (/packages/atom-silverstripe/node_modules/loophole/lib/loophole.js:14:14)
  at module.exports (/packages/atom-silverstripe/lib/logic.js:13:12)
  at /packages/atom-silverstripe/lib/silverstripe.js:19:29
  at Workspace.observeTextEditors (/app.asar/src/workspace.js:305:53)
  at /packages/atom-silverstripe/lib/silverstripe.js:8:16)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:826:28

```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-jade 0.3.0 
atom-silverstripe 3.0.2 
autocomplete-sass 0.1.0 
busy-signal 1.3.0 
color-picker 2.2.5 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
intentions 1.1.2 
language-haml 0.24.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jscs 4.1.2 
linter-jshint 3.0.3 
linter-php 1.3.2 
linter-phpmd 1.5.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-tidy 2.3.1 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
minimap 4.27.1 
project-manager 3.3.4 
project-sidebar 1.3.0 
react-es6-snippets 0.3.0 
tabs-to-spaces 1.0.3 
```

**Comment by gorriecoe** [comment]
I think this might be an issue with the detected version of silverstripe.   Since 3.0 this package now reads your composer.lock to determine the appropriate snippets.  Are you able to list the modules installed in your project and if they are using a dev version?

**Comment by grgcnnr** [comment]
here's the relevant chunk of my composer.json:
There's a few devs in there:
```
"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "3.4.*",
		"silverstripe/framework": "3.4.*",
		"silverstripe/reports": "3.4.*",
		"silverstripe/siteconfig": "3.4.*",
		"silverstripe-themes/simple": "3.1.*",
		"silverstripe/sqlite3": "1.4.0",
		"hubertusanton/silverstripe-seo": "^2.2",
		"sheadawson/silverstripe-linkable": "dev-master",
		"silverstripe/blog": "~2.4",
		"undefinedoffset/sortablegridfield": "^0.6.1",
		"jonom/focuspoint": "^2.1",
		"silverstripe/display-logic": "dev-master",
		"silverstripe/googlesitemaps": "^1.5",
		"andrelohmann-silverstripe/extended-image": "^1.1",
		"burnbright/silverstripe-hasonefield": "dev-master",
		"silverstripe/timepickerfield": "^1.0",
		"spekulatius/silverstripe-timezones": "^0.3.2",
		"marketo/silverstripe-regional": "dev-master",
		"geoip2/geoip2": "~2.0",
		"jonom/silverstripe-share-care": "^1.2",
		"sheadawson/silverstripe-dependentdropdownfield": "^1.0.4",
		"silverstripe-australia/gridfieldextensions": "^1.4",
		"sendgrid/sendgrid": "5.0.4",
		"zendesk/zendesk_api_client_php": "^2.1",
		"anahkiasen/underscore-php": "^2.0",
		"burnbright/silverstripe-pagesearch": "dev-master",
		"algolia/algoliasearch-client-php": "^1.11",
		"silverstripe/tagfield": "^1.3",
		"icecaster/versioned-gridfield": "dev-master",
		"guzzlehttp/guzzle": "^6.2",
		"tractorcow/silverstripe-colorpicker": "^3.0",
		"teodortalov/citrix": "dev-master",
		"littlegiant/silverstripe-batchwrite": "^0.3.0",
		"firebase/php-jwt": "^4.0"
	},
```

**Comment by gorriecoe** [comment]
Hey @grgcnnr,

I believe this should be resolved in the latest patch(3.0.3).  If you could update and confirm that would be awesome.

Cheers

**Comment by LiamW** [comment]
I upgraded and still getting the error.

`
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-silverstripe](https://github.com/gorriecoe/atom-silverstripe) package 3.0.3


### Stack Trace

Failed to activate the atom-silverstripe package

```
At Invalid or unexpected token

evalmachine.<anonymous>:1
1.x-dev >= 1.0
^^
SyntaxError: Invalid or unexpected token
  at Object.exports.runInThisContext (vm.js:76:16)
  at global.eval (/packages/atom-silverstripe/node_modules/loophole/lib/loophole.js:12:19)
  at /packages/atom-silverstripe/lib/logic.js:15:20
  at exports.allowUnsafeEval (/packages/atom-silverstripe/node_modules/loophole/lib/loophole.js:14:14)
  at module.exports (/packages/atom-silverstripe/lib/logic.js:13:12)
  at /packages/atom-silverstripe/lib/silverstripe.js:20:29
  at Workspace.observeTextEditors (/app.asar/src/workspace.js:305:53)
  at /packages/atom-silverstripe/lib/silverstripe.js:9:16)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:826:28

```

### Commands

```
     -0:27.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-next.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-silverstripe 3.0.3 
atom-zurb-foundation 2.0.0 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.3 
foundation5-snippets 0.2.2 
language-htaccess 0.1.1 
oceanic-next 1.0.0 
pigments 0.39.1 
project-manager 3.3.4 
```

`

**Comment by grgcnnr** [comment]
Hey @gorriecoe, patch looks good for me. It'll be a while before anything legitimately hits v9999 :)

**Comment by gorriecoe** [comment]
Thanks @grgcnnr.  @LiamW Can you list the packages used in your composer?  Cheers

**Comment by LiamW** [comment]
Sure thing!

		"silverstripe/cms": "3.5.*",
		"silverstripe/framework": "3.5.*",
		"silverstripe/googlesitemaps": "^1.6",
		"rywa/silverstripe-foundation-forms": "1.1.*@dev",
		"kinglozzer/metatitle": "^1.0",
		"silverstripe/blog": "^2.4",
		"silverstripe/spamprotection": "dev-master",
		"thezenmonkey/newrecaptcha": "dev-master",
		"tractorcow/silverstripe-dynamiccache": "4.1.*",
		"jonom/focuspoint": "^2.3"

**Comment by gorriecoe** [comment]
Hey @LiamW ,

Patch 3.0.4 should fix this.  If you could confirm that would be awesome.

Cheers

**Comment by LiamW** [comment]
Yup that fixes it. Thanks.
